#!/bin/bash

#open up the music player RhythmBox in my case
i3-msg 'workspace 8:; exec /usr/bin/rhythmbox' &&

#open up a volume control panel
i3-msg 'workspace 8:; exec /usr/bin/pavucontrol' &&

#split then merge the volume control with bluetooth control
i3 split h &&
i3 tabbed &&

i3-msg 'workspace 8:; exec /usr/bin/blueman-manager'
